/** FOR USER GET TEST */
export const USER_TEST_GET_REQUEST = "USER_TEST_GET_REQUEST";
export const USER_TEST_GET_SUCCESS = "USER_TEST_GET_SUCCESS";
export const USER_TEST_GET_ERROR = "USER_TEST_GET_ERROR";
/** for CRETE-test */
export const TEST_CREATE_REQUEST = "TEST_CREATE_REQUEST";
export const TEST_CREATE_SUCCESS = "TEST_CREATE_SUCCESS";
export const TEST_CREATE_ERROR = "TEST_CREATE_ERROR";

/** for get-test */
export const ADMIN_TEST_GET_REQUEST = "ADMIN_TEST_GET_REQUEST";
export const ADMIN_TEST_GET_SUCCESS = "ADMIN_TEST_GET_SUCCESS";
export const ADMIN_TEST_GET_ERROR = "ADMIN_TEST_GET_ERROR";

/** for update-test */
export const TEST_UPDATE_REQUEST = "TEST_UPDATE_REQUEST";
export const TEST_UPDATE_SUCCESS = "TEST_UPDATE_SUCCESS";
export const TEST_UPDATE_ERROR = "TEST_UPDATE_ERROR";

/** for DELETE-test */
export const TEST_DELETE_REQUEST = "TEST_DELETE_REQUEST";
export const TEST_DELETE_SUCCESS = "TEST_DELETE_SUCCESS";
export const TEST_DELETE_ERROR = "TEST_DELETE_ERROR";

/** for GET TEST BY ID */
export const USER_TEST_GET_BY_TEST_ID_REQUEST =
  "USER_TEST_GET_BY_TEST_ID_REQUEST";
export const USER_TEST_GET_BY_TEST_ID_SUCCESS =
  "USER_TEST_GET_BY_TEST_ID_SUCCESS";
export const USER_TEST_GET_BY_TEST_ID_ERROR = "USER_TEST_GET_BY_TEST_ID_ERROR";
